### ISSUE TITLE
upgrade mongodb dependency to support MongoDB 3.x

### ISSUE THREAD

**Issue by evandrix** [czzarr/node-stream-to-mongo#2]
Error encountered
```
MongoError: driver is incompatible with this server version
```
until I `cd $NODE_PATH/stream-to-mongo/package.json`, edit the `mongodb` dependency to `"*"`, and then `sudo npm install` to update `$NODE_PATH/stream-to-mongo/node_modules/mongodb`.

**Comment by czzarr** [comment]
Right, can you please send a PR with the correct version of the dependency?
